import type { Play } from './types';

export const plays: Play[] = [
  // Day 1 — The Quiet Superpower
  {
    id: 'still-stone',
    dayIndex: 0,
    slot: 'body',
    title: 'Still Stone',
    tagline: 'Your body can be a superpower when it stops',
    doAction: 'Stand like a stone for 60 seconds. Film yourself staying still — even when it gets itchy.',
    steps: [
      'Pick a spot in your room where you feel solid.',
      'Feet planted, shoulders loose, eyes soft.',
      'Hold still for 60 seconds. Timer on.',
      'Film the last 10 seconds — or your face right after.',
    ],
    openQuest: 'Notice one moment today when stillness would have helped. No need to tell anyone.',
    proofHint: 'Short video of you being still, or a selfie right after with "I did it" on a note.',
    durationMinutes: 7,
    engine: 'regulation',
    aesthetic: 'mist-blue',
    audioCue: 'Soft hum — low and steady.',
  },
  {
    id: 'flashlight-eyes',
    dayIndex: 0,
    slot: 'mind',
    title: 'Flashlight Eyes',
    tagline: 'See what everyone else walks past',
    doAction: 'Pick one ordinary object. Study it like it holds a secret. Photo + one sentence about what you found.',
    steps: [
      'Choose something boring: a shoe, a spoon, a crack in the wall.',
      'Look at it for 2 full minutes. No phone except the camera.',
      'Take a photo from the weirdest angle.',
      'Write one sentence: what did you notice that you never saw before?',
    ],
    openQuest: 'Use flashlight eyes on one person today — notice something kind about them.',
    proofHint: 'Photo of your object + note with your sentence.',
    durationMinutes: 8,
    engine: 'critical',
    aesthetic: 'amber-glow',
  },
  {
    id: 'silence-gift',
    dayIndex: 0,
    slot: 'people',
    title: 'Silence Gift',
    tagline: 'Sometimes the best thing you give is quiet',
    doAction: 'Spend 5 minutes near someone without filling the air with words. Write how it felt.',
    steps: [
      'Sit near a parent, sibling, or friend.',
      'No talking for 5 minutes. You can smile. You can breathe.',
      'After: one sentence — what was weird? what was good?',
    ],
    openQuest: 'Offer silence to someone who looks tired today.',
    proofHint: 'Photo of where you sat + your one-sentence note.',
    durationMinutes: 8,
    engine: 'social',
    aesthetic: 'soft-violet',
  },

  // Day 2 — Break It Then Build It
  {
    id: 'tower-crash',
    dayIndex: 1,
    slot: 'body',
    title: 'Tower Crash',
    tagline: 'Destroy on purpose, then build better',
    doAction: 'Build a tower of 10 things. Knock it down. Rebuild it completely different. Film the crash.',
    steps: [
      'Gather 10 items: books, boxes, cups — anything safe.',
      'Stack them tall.',
      'Knock it down on purpose. Film the crash.',
      'Rebuild using a different shape. Photo the new tower.',
    ],
    openQuest: 'Find one thing today you could rebuild a different way.',
    proofHint: 'Video of crash or photo of new tower.',
    durationMinutes: 10,
    engine: 'agency',
    aesthetic: 'copper-rust',
  },
  {
    id: 'parts-detective',
    dayIndex: 1,
    slot: 'mind',
    title: 'Parts Detective',
    tagline: 'Nothing is magic — everything has pieces',
    doAction: 'Take apart something SAFE (toy, pen, old remote with permission). Photo the parts laid out.',
    steps: [
      'Ask permission first. Only safe objects.',
      'Take it apart carefully.',
      'Lay pieces out like evidence.',
      'Photo from above. Guess what one piece does.',
    ],
    openQuest: 'Ask someone how something in your house actually works.',
    proofHint: 'Photo of parts laid out + your guess on a note.',
    durationMinutes: 12,
    engine: 'critical',
    aesthetic: 'workshop',
  },
  {
    id: 'fix-it-offer',
    dayIndex: 1,
    slot: 'people',
    title: 'Fix-It Offer',
    tagline: 'Builders show up',
    doAction: 'Find one small broken thing at home. Offer to help fix it. Note what happened.',
    steps: [
      'Spot something: loose hinge, tangled cord, messy drawer.',
      'Say: "Want help with that?"',
      'Do whatever they say — even if it\'s just holding something.',
      'One sentence: what did fixing feel like?',
    ],
    openQuest: 'Notice one thing that could be better — don\'t have to fix it today.',
    proofHint: 'Photo of what you helped with + short note.',
    durationMinutes: 10,
    engine: 'agency',
    aesthetic: 'warm-wood',
  },

  // Day 3 — People Radar
  {
    id: 'mirror-walk',
    dayIndex: 2,
    slot: 'body',
    title: 'Mirror Walk',
    tagline: 'Borrow confidence from someone you admire',
    doAction: 'Walk for 30 seconds like someone you admire. Film it. Write who and why.',
    steps: [
      'Pick a person: athlete, character, parent, friend.',
      'How do they stand? How do they move?',
      'Walk across the room that way for 30 seconds.',
      'Film it. Write their name and one trait you copied.',
    ],
    openQuest: 'Catch yourself walking like them once today outside this play.',
    proofHint: 'Video of mirror walk or photo + name note.',
    durationMinutes: 7,
    engine: 'social',
    aesthetic: 'mirror-silver',
  },
  {
    id: 'echo-game',
    dayIndex: 2,
    slot: 'mind',
    title: 'Echo Game',
    tagline: 'Listening is a stealth superpower',
    doAction: 'Repeat the last 3 words someone said to you today. Write who said it and what it meant.',
    steps: [
      'Think of a real conversation from today or yesterday.',
      'Write the last 3 words they said — exact words.',
      'Write who it was.',
      'One sentence: what were they really saying underneath?',
    ],
    openQuest: 'In your next conversation, echo back 3 words before you reply.',
    proofHint: 'Photo of your echo note (names can be initials).',
    durationMinutes: 8,
    engine: 'social',
    aesthetic: 'echo-teal',
  },
  {
    id: 'warm-open',
    dayIndex: 2,
    slot: 'people',
    title: 'Warm Open',
    tagline: 'Questions that aren\'t about school',
    doAction: 'Ask one person a question that has nothing to do with homework or grades.',
    steps: [
      'Think of someone: family, friend, teacher even.',
      'Ask something real: "What made you laugh lately?" "What are you curious about?"',
      'Listen. Don\'t fix. Don\'t one-up.',
      'Write their answer in one sentence (your words).',
    ],
    openQuest: 'Remember their answer tomorrow and follow up.',
    proofHint: 'Note with your question + their answer (no names needed).',
    durationMinutes: 10,
    engine: 'social',
    aesthetic: 'sunrise-coral',
  },

  // Day 4 — Cage or Door
  {
    id: 'tiger-breath',
    dayIndex: 3,
    slot: 'body',
    title: 'Tiger Breath',
    tagline: 'What rises when you make room',
    doAction: 'Three breath cycles: in 4, hold 4, out 6. Film your shoulders dropping on the last one.',
    steps: [
      'Name what feels stuck — one word is enough.',
      'Breathe: in 4, hold 4, out 6. Three times.',
      'Notice your shoulders. Let them drop.',
      'Film your face or shoulders after round 3.',
    ],
    openQuest: 'Use tiger breath once when something squeezes you today.',
    proofHint: 'Short video of breath finish or selfie after.',
    durationMinutes: 6,
    engine: 'regulation',
    aesthetic: 'tiger-ember',
    audioCue: 'In… hold… out… longer.',
  },
  {
    id: 'cage-sketch',
    dayIndex: 3,
    slot: 'mind',
    title: 'Cage Sketch',
    tagline: 'Cages aren\'t always bars',
    doAction: 'Draw a cage that isn\'t made of bars — rules, secrets, fear. Photo your drawing.',
    steps: [
      'Think: what traps people that you can\'t see?',
      'Draw it: a cage of words, expectations, silence, screens.',
      'Label one part.',
      'Photo your drawing.',
    ],
    openQuest: 'Notice a "cage" in a book or show you\'re reading — no quiz, just notice.',
    proofHint: 'Photo of your cage drawing.',
    durationMinutes: 10,
    engine: 'critical',
    aesthetic: 'ink-door',
  },
  {
    id: 'door-note',
    dayIndex: 3,
    slot: 'people',
    title: 'Door Note',
    tagline: 'One honest sentence opens something',
    doAction: 'Write one honest sentence to someone. Fold it. Photo the folded note (words hidden is OK).',
    steps: [
      'Pick someone you trust.',
      'Write ONE true sentence you usually don\'t say.',
      'Fold it. Give it, or keep it — your call.',
      'Photo the folded note (blur if you want).',
    ],
    openQuest: 'Leave a door open today — literal or metaphorical.',
    proofHint: 'Photo of folded note or envelope.',
    durationMinutes: 8,
    engine: 'agency',
    aesthetic: 'paper-gold',
  },

  // Day 5 — The 80/20 Game
  {
    id: 'sprint-stack',
    dayIndex: 4,
    slot: 'body',
    title: 'Sprint Stack',
    tagline: 'You choose the load — that\'s agency',
    doAction: 'Pick ONE: 20 jumping jacks OR 80 steps around your space. Film the finish.',
    steps: [
      'Choose your version. No one else picks.',
      'Do it. Full effort, not performative.',
      'Film the last 5 seconds or your feet when done.',
      'Notice: did you pick the easier one? That\'s data, not failure.',
    ],
    openQuest: 'Use the 80/20 rule on one chore today — smallest action, biggest result.',
    proofHint: 'Video finish or photo of step count on paper.',
    durationMinutes: 7,
    engine: 'agency',
    aesthetic: 'volt-green',
  },
  {
    id: 'smallest-win',
    dayIndex: 4,
    slot: 'mind',
    title: 'Smallest Win',
    tagline: 'What 20% gives you 80%?',
    doAction: 'Name the smallest school/life task that would make today feel handled. Photo your list.',
    steps: [
      'List 3 things on your plate (school or life).',
      'Circle the ONE that unlocks the rest.',
      'Do that one thing — or plan exactly when.',
      'Photo your list with the circle.',
    ],
    openQuest: 'Tell a parent which one you circled and why — 30 seconds max.',
    proofHint: 'Photo of list with circle.',
    durationMinutes: 10,
    engine: 'academic',
    aesthetic: 'focus-lime',
  },
  {
    id: 'energy-trade',
    dayIndex: 4,
    slot: 'people',
    title: 'Energy Trade',
    tagline: 'Sometimes you just listen',
    doAction: 'Ask someone what drained them today. Listen only. Write one word they felt.',
    steps: [
      'Find a person.',
      'Ask: "What drained you today?"',
      'Listen. No advice unless they ask.',
      'Write one word for their feeling.',
    ],
    openQuest: 'Protect your own energy once today — say no to one small drain.',
    proofHint: 'Note with one feeling word (no name required).',
    durationMinutes: 8,
    engine: 'social',
    aesthetic: 'drain-blue',
  },

  // Day 6 — Pressure Bridge
  {
    id: 'wall-push',
    dayIndex: 5,
    slot: 'body',
    title: 'Wall Push',
    tagline: 'Push pressure into the wall, not your chest',
    doAction: 'Push a wall hard for 30 seconds. Film your hands. Notice what shifts inside.',
    steps: [
      'Find a wall. Hands flat.',
      'Push like you\'re trying to move the house.',
      '30 seconds. Breathe.',
      'Step back. One word: lighter, same, or heavier?',
    ],
    openQuest: 'When stress hits today, push a wall before you snap at someone.',
    proofHint: 'Video of wall push or photo of hands on wall.',
    durationMinutes: 6,
    engine: 'regulation',
    aesthetic: 'concrete-grey',
  },
  {
    id: 'pressure-name',
    dayIndex: 5,
    slot: 'mind',
    title: 'Pressure Name',
    tagline: 'Named pressure is smaller pressure',
    doAction: 'Write 3 words for what\'s squeezing you. Photo the paper.',
    steps: [
      'No fixing yet. Just name.',
      'Three words: test, friend, tired, noise, whatever.',
      'Big letters on paper.',
      'Photo it. You can crumple it after.',
    ],
    openQuest: 'Tell one word to someone safe — or keep it. Your call.',
    proofHint: 'Photo of 3-word paper.',
    durationMinutes: 7,
    engine: 'regulation',
    aesthetic: 'compress-purple',
  },
  {
    id: 'load-share',
    dayIndex: 5,
    slot: 'people',
    title: 'Load Share',
    tagline: 'Strong people ask for help',
    doAction: 'Ask someone to help with one tiny thing. Note what happened.',
    steps: [
      'Pick something small: open a jar, find a sock, read one line.',
      'Ask: "Can you help me with this?"',
      'Let them help. Say thanks.',
      'One sentence: easier, awkward, or surprising?',
    ],
    openQuest: 'Offer to carry someone\'s load once today — literally or not.',
    proofHint: 'Note with what happened.',
    durationMinutes: 8,
    engine: 'agency',
    aesthetic: 'bridge-teal',
  },

  // Day 7 — One Honest Move
  {
    id: 'brave-stand',
    dayIndex: 6,
    slot: 'body',
    title: 'Brave Stand',
    tagline: 'Stand where you usually hide',
    doAction: 'Stand in a spot you usually avoid (front of room, center of kitchen). 10 seconds on film.',
    steps: [
      'Notice where you usually shrink: corner, back, doorway.',
      'Go to the open spot.',
      'Stand tall 10 seconds.',
      'Film it or photo from your POV.',
    ],
    openQuest: 'Take one honest stand today — small counts.',
    proofHint: 'Video or POV photo from the brave spot.',
    durationMinutes: 6,
    engine: 'agency',
    aesthetic: 'brave-gold',
  },
  {
    id: 'one-true-line',
    dayIndex: 6,
    slot: 'mind',
    title: 'One True Line',
    tagline: 'Truth doesn\'t have to be loud',
    doAction: 'Write one true thing you usually don\'t say. Photo blurred is OK.',
    steps: [
      'One sentence. Handwritten.',
      'It can be small: "I was scared" "I liked it" "I need help."',
      'Photo it — blur if you want.',
      'Keep it or tear it up after.',
    ],
    openQuest: 'Say one true line out loud to yourself in the mirror.',
    proofHint: 'Blurred photo of note or typed note screenshot.',
    durationMinutes: 8,
    engine: 'agency',
    aesthetic: 'truth-indigo',
  },
  {
    id: 'smallest-promise',
    dayIndex: 6,
    slot: 'people',
    title: 'Smallest Promise',
    tagline: 'Reliability starts tiny',
    doAction: 'Make one tiny promise today and keep it. Proof: note what you promised and that you did it.',
    steps: [
      'Promise something you WILL do: "I\'ll clear my plate" "I\'ll text grandma hi."',
      'Write it down.',
      'Do it before bed.',
      'Check the box. Photo the note.',
    ],
    openQuest: 'Notice who keeps small promises around you — copy them.',
    proofHint: 'Note with promise + checkmark.',
    durationMinutes: 10,
    engine: 'agency',
    aesthetic: 'promise-rose',
  },
];

export function getPlaysForDay(dayIndex: number): Play[] {
  return plays.filter((p) => p.dayIndex === dayIndex);
}

export function getPlay(id: string): Play | undefined {
  return plays.find((p) => p.id === id);
}

export const PLAY_TITLES = plays.map((p) => p.title);
